import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SpeedInsights } from '@vercel/speed-insights/next'

import { cn } from '@/lib/utils'

import './globals.css'

const inter = Inter({ subsets: ['latin'], weight: '500' })

export const metadata: Metadata = {
  title: 'EBRAINS',
  description: 'Generated by yungrari',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'overflow-hidden')}>
        {children}
        <SpeedInsights />
      </body>
    </html>
  )
}
