import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], weight: '500' })

export const metadata: Metadata = {
  title: 'EBRAINS',
  description: 'Generated by yungrari',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overscroll-none overflow-hidden`}>
        {children}
      </body>
    </html>
  )
}
